spring:
  application:
    name: aggregator
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topic:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    ru.practicum.aggregator: DEBUG