CREATE TABLE IF NOT EXISTS public.ratings (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    event_id bigint NOT NULL,
    reaction varchar(10) NOT NULL CHECK (reaction IN ('LIKE', 'DISLIKE')),
    CONSTRAINT pk_ratings PRIMARY KEY (id),
    CONSTRAINT uq_ratings_user_event UNIQUE (user_id, event_id)
    );