CREATE TABLE IF NOT EXISTS public.requests (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp(3) without time zone,
    status varchar(255) check (status in ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
    event_id bigint,
    requester_id bigint,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);
