server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/analyzer
    username: analyzer
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  sql:
    init:
      mode: always
      continue-on-error: true

kafka:
  consumer:
    user-actions:
      group-id: analyzer-user-actions-group
      properties:
        enable.auto.commit: false
        auto.offset.reset: earliest
        max.poll.records: 100
    events-similarity:
      group-id: analyzer-events-similarity-group
      properties:
        enable.auto.commit: false
        auto.offset.reset: latest
        max.poll.records: 100
logging:
  level:
    ru.practicum.analyzer: DEBUG